site_name: My Docs

theme:
  name: material

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true


# site_name: My Docs
# nav:
#   - Home: index.md
#   - About: about.md
# theme:
#   name: mkdocs
# markdown_extensions:
#   - admonition
#   - codehilite
#   - toc:
#       permalink: true
