services:

# =========== Redis

  redis_root:
    container_name: redis_container
    image: redis/redis-stack:latest
    ports:
      - "31001:6379"
      - "31002:8001"
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
    networks:
      eprnet:
        ipv4_address: 172.16.238.11

  redis-ui-root:
    container_name: redis_ui_container
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: "local:redis_container:6379"
    ports:
      - "31003:8081"
    volumes:
      - ./redis_ui_data:/data
    depends_on:
      - redis_root
    networks:
      eprnet:
        ipv4_address: 172.16.238.15
# =========== End Redis

networks:
  eprnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

